import { Public_Sans } from 'next/font/google';
import './globals.css';

const public_sans = Public_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
  style: ['normal', 'italic'],
  variable: '--font-sans',
})

export const metadata = {
  title: 'Robust Dasboard',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={public_sans.className}>
      <body>
        {/* <Navbar /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
